_BASE_: "Base-SparseRCNN.yaml"
MODEL:
    WEIGHTS: "torchvision-R-101.pkl"
    RESNETS:
        DEPTH: 101
        STRIDE_IN_1X1: False
    SparseRCNN:
        NUM_PROPOSALS: 300
INPUT:
    CROP:
        ENABLED: True
