_BASE_: "Base-SparseRCNN.yaml"
MODEL:
    WEIGHTS: "torchvision-R-101.pkl"
    RESNETS:
        DEPTH: 101
        STRIDE_IN_1X1: False
    SparseRCNN:
        NUM_PROPOSALS: 100
SOLVER:
    STEPS: (210000, 250000)
    MAX_ITER: 270000
INPUT:
    CROP:
        ENABLED: False
